# Generated by Django 3.1.5 on 2021-01-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testcovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=100)),
                ('pdf', models.CharField(max_length=100)),
                ('specialist', models.CharField(max_length=100)),
                ('pcr', models.CharField(max_length=100)),
                ('creation_date', models.CharField(max_length=100)),
            ],
        ),
    ]
