# Generated by Django 3.1.6 on 2021-02-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartConsentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idb', models.CharField(max_length=100)),
                ('field1', models.TextField()),
                ('field2', models.TextField()),
                ('field3', models.TextField()),
                ('field4', models.TextField()),
                ('creation_date', models.CharField(max_length=100)),
            ],
        ),
    ]
