class UserModel {
  String login;
  String avatar_url;

  UserModel({this.login, this.avatar_url});

  factory UserModel.fromJson(Map<String, dynamic> json) {
    return UserModel(
      login: json['login'],
      avatar_url: json['avatar_url'],
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['login'] = this.login;
    data['avatar_url'] = this.avatar_url;
    return data;
  }
}

class Users {
  List<User> usuarios = new List();

  Users();

  Users.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    // jsonList.forEach((item) {
    //   final user = User.fromJsonMap(item);
    //   usuarios.add(user);
    // });
    for (var item in jsonList) {
      final user = new User.fromJsonMap(item);
      item.add(
          user); //aqui se agrega el map ya con el procesp de arriba de JsonMap
    }
  }
}

class User {
  int idPatient;
  String noClinicHistory;
  String dni;
  String picture;
  String namePatient;
  String lastname;

  User({
    this.idPatient,
    this.noClinicHistory,
    this.dni,
    this.picture,
    this.namePatient,
    this.lastname,
  });

  User.fromJsonMap(Map<String, dynamic> json) {
    idPatient = json['id_patient'];
    noClinicHistory = json['no_clinic_history'];
    dni = json['dni'];
    picture = json['picture'];
    namePatient = json['name_patient'];
    lastname = json['lastname'];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();

    return data;
  }
}





// Generated by https://quicktype.io


