import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:SmartConsent/Models/UserModel.dart';
import 'package:SmartConsent/Screens/auth/consent/Login/components/body.dart';
import 'package:SmartConsent/Screens/pdfViewer/components/pdfBody.dart';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:nb_utils/nb_utils.dart';

class UserProvider {
  // ignore: missing_return
  Future<http.Response> authRequest(String name, String pass) async {
    try {
      print("entro a post");
      var url = 'http://172.245.159.100:3000/gen-query';
      Map data = {
        "process": "",
        "request": "get-login",
        "data": {"login": name, "password": pass}
      };
      //encode Map to JSON
      var body = json.encode(data);
      final response = await http.post(Uri.parse(url),
          headers: {"Content-Type": "application/json"}, body: body);
      final decodedData = json.decode(response.body);
      print(decodedData[0]['answer']['correct']);
      if (decodedData[0]['answer']['resp'][0]['id_user'] != null) {
        print('User correct');
        Body().correctUser();
      } else {
        print('User incorrect');
      }
      return response;
    } catch (e) {
      toast('Fail in credentials');
      print('error$e');
    }
  }
}

class UserGetProvider {
  // ignore: missing_return
  Future<http.Response> getUserRequest() async {
    try {
      print("entro a post");
      var url = '172.245.159.100:3000/gen-query';
      Map data = {"process": "", "request": "patients"};
      //encode Map to JSON
      var body = json.encode(data);
      final response = await http.post(Uri.parse(url),
          headers: {"Content-Type": "application/json"}, body: body);
      final decodedData = json.decode(response.body);
      // final usr = new Users.fromJsonList(decodedData['answer']);
      // print("${response.statusCode}");
      // print("${response.body}");
      // print("sdsdsdsds ${LoginModel().id_user}");
      print(decodedData);
      final usuarios = new Users.fromJsonList(decodedData[0]['answer']);
      print(usuarios);
      // Map datamap = json.decode()
      return response;
    } catch (e) {
      print('error :::::::::::::::::::::::::::::::::::$e');
    }
  }

  // ignore: missing_return
  Future getConsents(int valuConsultText) async {
    try {
      print("entro a post");
      var url = 'http://172.245.159.100:3000/get-process-detail-crt';
      Map data = {
        "idCatProcess": {"procedures": "0,0,1,0,0", "specialties": "0,0,0"}
      };

      //encode Map to JSON
      var body = json.encode(data);
      final response = await http.post(Uri.parse(url),
          headers: {"Content-Type": "application/json"}, body: body);
      final decodedData = json.decode(response.body);
      final responseData = decodedData['resp'][0]['header'][0]
          ['structure_screens']['order'][valuConsultText]['text'];
      print(decodedData['resp'][0]['header'][0]['structure_screens']['order']
              [valuConsultText]
          ['text']); //Hacer un modelo para recibir estos datos;
      return responseData;
    } catch (e) {
      print('error:$e');
    }
  }
}

class UserGenertaePdf {
  var firmaEspecialista;
  var firmaPaciente;
  var userName = '';
  var userDni = '';

  dataUSerData(
      String name, String lastaname, String din, String dataCreation) {}

  firmaPAciente(String data) {
    firmaPaciente = data;
  }

  firmaEspecialis(String data) {
    firmaEspecialista = data;
    // print('datoespecialista$firmaEspecialista');
  }

  // ignore: missing_return
  Future<http.Response> generatePdf() async {
    try {
      print("entro a post");
      var url = 'http://172.245.159.100:3000/send-consent-crt';
      //send data to ipfs example
      Map data = {
        "consent": {"idUser": 1, "idSpecialist": 1},
        "pdf": {
          "header": {
            "text1": "",
            "text2": "Test document and worthless",
            "text3": "{centro_de_salud.logo}",
            "text4": "Internet",
            "text5": "www.smartconsent.com",
            "text6": "Document generated by ©SmartConset"
          },
          "body": {
            "text": [
              {
                "order": 2,
                "information":
                    "Difficulties\r\n\r\nWhite spots may appear on the teeth during the treatment. These stains usually disappear as the tooth lightens its color. However, sometimes they may remain present at the end of it, and it will be necessary to put into practice other therapeutic alternatives if it is desired to eliminate them.\r\n\r\nThe cervical area of the tooth may be more resistant to treatment and not reach achieve the same color as the rest of it.\r\n\r\nnOccasionally the teeth may not change their color with the treatment.\r\n\r\n To maintain the results achieved after the treatment, it may be necessary to repeat this periodically when the dentist deems it convenient, or put into practice the maintenance measures that he considers most appropriate.\r\n\r\nProbable risks under normal conditions\r\n\r\nTreatments that the patient performs at home They can damage the gums or cause discomfort if they are not carried out properly, or the time or number of times of application of the product per day, or the amount of application of the same is exceeded. \r\n\r\nIf too much gel is applied causing contact with the gums, it should be removed with a gauze, as irritation can occur in the same.\r\n\r\nThe metal fillings can be altered if they come into contact with the product. If they are Ingested accidentally, you can occasionally suffer from throat discomfort or even have a mild episode of diarrhea. \r\n\r\nDuring treatment you may have sensitivity or discomfort in the teeth after ingesting hot, cold drinks and / or foods, acidic or carbonated drinks, as well as the possible possibility of presenting an allergy to some bleaching products. If this happens, the clinic should be contacted.\r\nThere is a risk of a certain root resorption, especially when it is carried out on teeth that have been endodontically treated or have suffered trauma, although this risk is very low\r\n\r\nParticular circumstances of the patient:\r\n\r\nIf you are a smoker, or you do not have good oral hygiene or you eat many foods or drinks rich in colorants, your teeth will darken more quickly than if not, despite the fact that your teeth darken physiologically with age.\r\n\r\nIn highly restored teeth, whitening may not be very effective as they do not present sufficient tooth structure.\r\n\r\nThe whitening treatment does not modify the color of fillings, veneers, crown and other materials placed on my teeth. In these cases there are other more suitable alternatives when it comes to modifying the color of the teeth.\r\nIf the teeth have bands or spots, these can still be noticed, although lighter.\r\n"
              },
              {
                "order": 1,
                "information":
                    "DECLARATION OF INFORMATION FOR CONSENT\r\n\r\nnOVER WHITENING\r\n\r\nI, $userName with NIF / Passport  $userDni, declare that with date {consent.date_creation} , at {centro_de_salud.nombre}, the physician {specialist.name} {specialist.lastname} collegiate {specialist.Collegiatura} has proposed and budgeted the following treatment plan:\r\n\r\nCovid 19 pandemic\r\n\r\nThe patient has been informed of the biosafety protocols established in {centro_de_salud.nombre} in the face of the new situation created by the COVID-19 PANDEMIC.\r\n\r\nIn the exceptional circumstance derived from the COVID-19 PANDEMIC, we inform you that it is NOT possible to ensure a NULL RISK of transmission of COVID-19 despite the fact that the Donnay Dental Clinic has established strict protocols to ensure the maximum safety of patients and professionals.\r\n\r\nINFORMATION ON WHITENING\r\n\r\nPurpose:\r\n\r\nClarify the color of the teeth, vital or not, achieving a whiter tone. The degree of improvement in the tone of the teeth will depend on each person and their teeth, being more difficult in cases of having fillings or intrinsic stains and bands, since only the dental tissue will be whitened and equally, not eliminating stains of selective mode.\r\n\r\nNature of the treatment:\r\n\r\nConsists of:\r\n\r\n- Placing a whitening gel on the external surface of the teeth whitening.\r\n\r\n- Placement on the teeth of soft silicone trays, made to measure and that will be delivered in the consultation.\r\n\r\n- Joint use of the two techniques described above .\r\n\r\n- In the consultation application of a whitening gel on the external surface of the teeth.\r\n\r\n- In the application of a whitening gel and a protector for my gums and the eyes, during a time that the professional will decide and applying a light source on the teeth.\r\n\r\n- When the treatment is carried out in the consultation To exclusively, several sessions may be necessary to achieve satisfactory results.\r\n\r\n- Before starting the whitening treatment in the consultation, adequate protection of the gums and teeth that are not going to be bleached is necessary.\r\n\r\n"
              },
              {
                "order": 3,
                "information":
                    "The patient assumes that the initially prescribed treatment plan is indicative and that it may undergo modifications depending on the response of the teeth to it.\r\n\r\nAll instructions and recommendations indicated by the dentist must be strictly followed and Comply with the scheduled review program.\r\n\r\nDECLARATION OF CONSENT\r\n\r\nPATIENT\r\n\r\nD/Mrs {patient.name} {patient.last name} with ID { patient.dni}, or his Legal Representative M / M. {patient.rep_name} {patient.rep_lastname} with ID {patient.rep_dni}:\r\n\r\nI declare that the practitioner Dr./Dra. { specialist.name} {specialist.lastname} has satisfactorily explained to me what this treatment is, how it is performed and what it is for. He has also explained the existing risks, possible discomfort or complications, that this is the most appropriate procedure for me current clinical situation, and the foreseeable consequences of its non-performance.\r\n\r\nI have fully understood All of the above, and for all of this, on this date I consent that Dr. {specialist.name} {specialist.lastname} and therefore the team of clinic assistants that he / she designates, perform the aforementioned treatment reserving me the right to revoke at any time this consent that I now give, without the need to give any explanation.\r\n\r\nWhat in proof of the above I sign in {city.name} to {consent.creation_date}\r\n"
              },
              {
                "order": 4,
                "information":
                    "OPTIONAL\r\n\r\n Dr./Dra. {Specialist.name} {specialist.lastname} Col. No. {specialist.collegiate} I have informed this patient and / or his legal representative, of the purpose and nature of the described procedure, its risks and alternatives, and the foreseeable consequences of not performing it, leaving a record in the clinical history. Likewise, he was asked about his possible allergies, the existence of other diseases or any personal pathological circumstance that could condition the performance This document is incorporated into the patient's medical record.\r\nWhat I sign in {city.name} to {consent.creation_date}\r\n\r\nAudio ID: {audio .md5}\r\nVideo ID: {video.hashmd5}\r\nID Patient Signature: {consent.hash_fpatient}\r\nID Signature Legal Representative: {consent.hash_frepresentante}\r\nID Signature Specialist: {consent.hash_fespecialista } "
              }
            ],
            "firmas": {
              "firma_p": firmaPaciente,
              "firma_e": firmaEspecialista,
            }
          }
        }
      };

      //encode Map to JSON
      var body = json.encode(data);
      final response = await http.post(Uri.parse(url),
          headers: {"Content-Type": "application/json"}, body: body);
      final decodedData = json.decode(response.body);
      // final usr = new Users.fromJsonList(decodedData['answer']);
      // print("${response.statusCode}");
      // print("${response.body}");
      // print("sdsdsdsds ${LoginModel().id_user}");
      print(decodedData['resp']);
      // GetUrl().getUrl(
      //     decodedData['resp']['urlipfs'],
      //     decodedData['resp']['hashpdf']);

      final usuarios = new Users.fromJsonList(decodedData);
      print(usuarios);

      // Map datamap = json.decode()

      return response;
    } catch (e) {
      print('error :::::::::::::::::::::::::::::::::::$e');
    }
  }
}
